# Generated by Django 3.1.5 on 2021-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DateAdded',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.TextField(default='xyz@gmail.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='First_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Parent_name',
            field=models.CharField(max_length=100),
        ),
    ]
