# Generated by Django 3.1.5 on 2021-01-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0002_auto_20210125_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DateAdded',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='DateUpdated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Date_of_birth',
            field=models.DateField(),
        ),
    ]
