# Generated by Django 3.1.5 on 2021-01-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0004_student_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Class',
        ),
    ]
